// Generated by CoffeeScript 1.12.4
(function() {
  var autoprefixer, babel, browserSync, concat, csso, del, fileinclude, gulp, minify, plumber, runSequence, sass, sourcemaps, spriter, uglify;

  gulp = require('gulp');

  fileinclude = require('gulp-file-include');

  minify = require('gulp-minify-css');

  sass = require('gulp-sass');

  browserSync = require('browser-sync');

  del = require('del');

  runSequence = require('run-sequence');

  concat = require('gulp-concat');

  uglify = require('gulp-uglify');

  autoprefixer = require('gulp-autoprefixer');

  spriter = require('gulp-css-spriter');

  plumber = require('gulp-plumber');

  csso = require('gulp-csso');

  babel = require('gulp-babel');

  sourcemaps = require("gulp-sourcemaps");

  gulp.task('default', function(callback) {
    return runSequence(['clean'], ['build'], ['serve', 'watch'], callback);
  });

  gulp.task('clean', function(callback) {
    return del(['./dist/'], callback);
  });

  gulp.task('build', function(callback) {
    return runSequence(['concatHtml', 'copy'], ['sassCss', 'miniJs'], callback);
  });

  gulp.task('sassCss', function() {
    return gulp.src('./src/scss/*.scss').pipe(plumber()).pipe(sourcemaps.init()).pipe(sass()).pipe(autoprefixer({
      browsers: ['last 5 versions', 'Android >= 4.0', '> 1%', 'Firefox >= 20', 'Firefox ESR', 'ie 8', 'IOS 7'],
      cascade: true,
      remove: true,
      add: true,
      flexbox: true
    })).pipe(minify()).pipe(sourcemaps.write(".")).pipe(plumber.stop()).pipe(gulp.dest('./dist/css'));
  });

  gulp.task('miniJs', function() {
    gulp.src('./src/component/**/**/*.js').pipe(plumber()).pipe(concat('all.js', {
      newLine: ';\n'
    })).pipe(uglify()).pipe(plumber.stop()).pipe(gulp.dest('./dist/js/'));
    return gulp.src(['./src/js/bootstrap.js', './src/js/script.js']).pipe(plumber()).pipe(plumber.stop()).pipe(gulp.dest('./dist/js/'));
  });

  gulp.task('concatHtml', function() {
    return gulp.src(["./src/page/*.html"]).pipe(plumber()).pipe(fileinclude({
      prefix: '@@',
      basepath: '@file',
      context: {
        name: 'test'
      }
    })).pipe(plumber.stop()).pipe(gulp.dest('./dist/'));
  });

  gulp.task('copy', function() {
    gulp.src('./src/js/*.js').pipe(gulp.dest('./dist/js/'));
    gulp.src('./src/js/jqx/*.*').pipe(gulp.dest('./dist/js/jqx/'));
    gulp.src('./src/fonts/*.*').pipe(gulp.dest('./dist/fonts/'));
    return gulp.src('./src/img/*.*').pipe(gulp.dest('./dist/img/'));
  });

  gulp.task('serve', function() {
    return browserSync.init({
      server: {
        baseDir: './dist/'
      },
      port: 7413
    });
  });

  gulp.task('watch', function() {
    return gulp.watch('./src/**/*.*', ['reload']);
  });

  gulp.task('reload', function(callback) {
    return runSequence(['build'], ['reload-browser'], callback);
  });

  gulp.task('reload-browser', function() {
    return browserSync.reload();
  });

}).call(this);

//# sourceMappingURL=gulpfile.js.map
