// Generated by CoffeeScript 1.12.4
(function() {
  var autoprefixer, babel, browserSync, changed, concat, del, fileinclude, gulp, imagemin, minify, plumber, rename, replace, runSequence, sass, sourcemaps, uglify;

  gulp = require('gulp');

  fileinclude = require('gulp-file-include');

  minify = require('gulp-clean-css');

  sass = require('gulp-sass');

  browserSync = require('browser-sync');

  del = require('del');

  runSequence = require('run-sequence');

  concat = require('gulp-concat');

  uglify = require('gulp-uglify');

  autoprefixer = require('gulp-autoprefixer');

  plumber = require('gulp-plumber');

  babel = require('gulp-babel');

  sourcemaps = require("gulp-sourcemaps");

  replace = require("gulp-replace");

  rename = require("gulp-rename");

  imagemin = require('gulp-imagemin');

  changed = require('gulp-changed');

  gulp.task('default', function(callback) {
    return runSequence(['clean'], ['build'], ['serve', 'watch'], callback);
  });

  gulp.task('clean', function(callback) {
    return del(['./dist/'], callback);
  });

  gulp.task('build', function(callback) {
    return runSequence(['concatHtml', 'copy'], ['sassCss', 'miniJs', 'miniImg'], callback);
  });

  gulp.task('reserve', function() {
    return runSequence(['concatHtml'], ['sassCss'], ['miniJs']);
  });

  gulp.task('sassCss', function() {
    return gulp.src('./src/scss/*.scss').pipe(changed('./dist/css', {
      hasChanged: changed.compareSha1Digest
    })).pipe(sourcemaps.init()).pipe(plumber()).pipe(sass()).pipe(autoprefixer({
      browsers: ['last 5 versions', 'Android >= 4.0', '> 1%', 'Firefox >= 20', 'Firefox ESR', 'ie 8', 'IOS 7'],
      cascade: true,
      remove: true,
      add: true,
      flexbox: true
    })).pipe(minify()).pipe(sourcemaps.write('./map')).pipe(plumber.stop()).pipe(gulp.dest('./dist/css'));
  });

  gulp.task('miniJs', function() {
    return gulp.src('./src/js/*.js').pipe(changed('./dist/js', {
      hasChanged: changed.compareSha1Digest
    })).pipe(plumber()).pipe(plumber.stop()).pipe(gulp.dest('./dist/js/'));
  });

  gulp.task('miniImg', function() {
    return gulp.src('./src/img/*.*').pipe(changed('./dist/img', {
      hasChanged: changed.compareSha1Digest
    })).pipe(plumber()).pipe(plumber.stop()).pipe(gulp.dest('./dist/img/'));
  });

  gulp.task('concatHtml', function() {
    return gulp.src(["./src/page/*.html"]).pipe(changed('./dist/', {
      hasChanged: changed.compareSha1Digest
    })).pipe(plumber()).pipe(fileinclude({
      prefix: '@@',
      basepath: '@file',
      context: {
        name: 'test'
      }
    })).pipe(plumber.stop()).pipe(gulp.dest('./dist/'));
  });

  gulp.task('copy', function() {
    gulp.src(['./src/js/bootstrap.js', './src/js/script.js']).pipe(changed('./dist/js', {
      hasChanged: changed.compareSha1Digest
    })).pipe(plumber()).pipe(uglify()).pipe(plumber.stop()).pipe(gulp.dest('./dist/js/'));
    gulp.src('./src/js/jqx/*.js').pipe(changed('./dist/js/jqx/', {
      hasChanged: changed.compareSha1Digest
    })).pipe(plumber()).pipe(uglify()).pipe(plumber.stop()).pipe(gulp.dest('./dist/js/jqx/'));
    return gulp.src('./src/fonts/*.*').pipe(changed('./dist/fonts', {
      hasChanged: changed.compareSha1Digest
    })).pipe(gulp.dest('./dist/fonts/'));
  });

  gulp.task('serve', function() {
    return browserSync.init({
      server: {
        baseDir: './dist/'
      },
      port: 7413
    });
  });

  gulp.task('watch', function() {
    gulp.watch('./src/js/*.js', ['miniJs']);
    gulp.watch('./src/scss/**/*.scss', ['sassCss']);
    gulp.watch(['./src/page/*.html', './src/component/**/*.html'], ['concatHtml']);
    return runSequence(['reload-browser']);
  });

  gulp.task('reload', function(callback) {
    return runSequence(['build'], ['reload-browser'], callback);
  });

  gulp.task('reload-browser', function() {
    return browserSync.reload();
  });

}).call(this);

//# sourceMappingURL=gulpfile.js.map
